name: Build Project
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet Packages
        run: msbuild chuni-hands.sln -t:restore

      - name: Build Solution
        run: msbuild chuni-hands.sln /t:Build /p:Configuration=Release /p:Platform=x64

      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: compiled-program
          path: "**/x64/Release/"
